//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaniShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Details
    {
        public int id { get; set; }
        public int Sales_id { get; set; }
        public int Product_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Product_price { get; set; }
        public int SubTotal { get; set; }
        public string salesdate { get; set; }
    }
}
